import os
import uuid
import asyncio
import logging
import io
from typing import List, Optional, Dict
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
import google.generativeai as genai
from fpdf import FPDF

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="ZeroToOne AI Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Models
class MarketSize(BaseModel):
    amount: str = Field(description="The dollar amount (e.g. $10B)")
    description: str = Field(description="Brief context / description.")
    growth: str = Field(description="Estimated year-over-year growth percentage (e.g. 15%)")

class MarketAnalysis(BaseModel):
    region_focus: str = Field(description="The geographic focus of this analysis (e.g. 'Global', 'India', 'United States'). Detect from input if possible.")
    tam: MarketSize
    sam: MarketSize
    som: MarketSize
    trends: List[str] = Field(description="3-5 key market trends.")

class Competitor(BaseModel):
    name: str
    description: str
    share: str

class CompetitiveLandscape(BaseModel):
    competitors: List[Competitor]
    differentiation: str
    moat: str

class Persona(BaseModel):
    name: str
    segment: str
    goals: List[str]
    pain_points: List[str]

class MVPSpec(BaseModel):
    features: List[str]
    user_flows: List[str]

class BudgetAndTeam(BaseModel):
    cost: str
    roles: List[str]
    hiring_plan: str

class GTMStrategy(BaseModel):
    channels: List[str]
    messaging: str
    metrics: List[str]

class Timeline(BaseModel):
    roadmap_12_months: List[str]

class Investor(BaseModel):
    name: str
    focus: str
    fit_score: int

class Blueprint(BaseModel):
    market_analysis: MarketAnalysis
    competitive_landscape: CompetitiveLandscape
    personas: List[Persona]
    mvp_spec: MVPSpec
    budget_and_team: BudgetAndTeam
    gtm_strategy: GTMStrategy
    timeline: Timeline
    investor_suggestions: List[Investor]

class GenerateRequest(BaseModel):
    idea: str
    api_key: str

class RegenerateRequest(BaseModel):
    id: str
    section: str
    api_key: str

# In-memory DB
blueprints_db: Dict[str, dict] = {}

async def call_llm_with_retry(prompt: str, response_model, api_key: str, max_retries=3):
    """Call Gemini with retry logic. Configures genai with the provided API key."""
    genai.configure(api_key=api_key)
    models = ["gemini-flash-latest", "gemini-2.0-flash", "gemini-1.5-flash"]
    
    for attempt in range(max_retries):
        for model_name in models:
            try:
                full_model_name = model_name if model_name.startswith("models/") else f"models/{model_name}"
                model = genai.GenerativeModel(full_model_name)
                response = model.generate_content(
                    prompt,
                    generation_config=genai.GenerationConfig(
                        response_mime_type="application/json",
                        response_schema=response_model,
                        temperature=0.7
                    )
                )
                return response_model.model_validate_json(response.text)
            except Exception as e:
                logger.error(f"Error with {model_name} on attempt {attempt+1}: {e}")
                await asyncio.sleep(2 ** attempt)
    
    raise Exception("All LLM models and retries failed.")

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(37, 99, 235)  # Blue 600
        self.cell(0, 10, 'ZeroToOne AI Startup Blueprint', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by ZeroToOne AI © 2026', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_fill_color(248, 250, 252)
        self.set_text_color(37, 99, 235)
        self.cell(0, 10, title, 0, 1, 'L', fill=True)
        self.ln(4)

    def section_body(self, body):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(30, 41, 59)
        self.multi_cell(0, 5, body)
        self.ln()

@app.post("/generate-blueprint")
async def generate_blueprint(request: GenerateRequest):
    if not request.api_key or not request.api_key.strip():
        raise HTTPException(status_code=400, detail="Gemini API key is required.")
    
    logger.info(f"Generating blueprint for idea: {request.idea}")
    
    prompt = f"""
    Analyze the following startup idea and generate a comprehensive, high-fidelity startup blueprint.
    
    STARTUP IDEA: "{request.idea}"
    
    INSTRUCTIONS:
    1. GEOGRAPHY: Detect the target region from the idea. If not specified, use 'Global'.
    2. INDUSTRY: Detect the specific industry domain.
    3. MARKET DATA: Provide realistic, professional-grade TAM, SAM, and SOM numbers. Include a realistic YoY growth percentage for each.
    4. TRENDS: Identify 3-5 specific, current market trends that directly impact this business model. Avoid generic buzzwords.
    5. COMPETITION: Identify 2-3 REAL existing competitors or major players in this space.
    6. STRATEGIC MOAT: Define a multi-layered defense (e.g. network effects, IP, high switching costs) specific to this startup.
    7. GTM & INVESTORS: Provide 2-3 REAL venture capital firms or investors that actively fund startups in this specific industry.
    
    Format the output strictly according to the provided JSON schema. Ensure 100% dynamic content based ONLY on the user's idea.
    """
    
    try:
        blueprint_data = await call_llm_with_retry(prompt, Blueprint, request.api_key)
        blueprint_dict = blueprint_data.model_dump()
        
        blueprint_id = str(uuid.uuid4())
        blueprints_db[blueprint_id] = {
            "id": blueprint_id,
            "idea": request.idea,
            "blueprint": blueprint_dict
        }
        return blueprints_db[blueprint_id]
        
    except Exception as e:
        logger.error(f"AI generation failed: {e}")
        raise HTTPException(
            status_code=429, 
            detail="AI generation failed. Please check your API key is valid and try again."
        )

@app.get("/export-pdf/{blueprint_id}")
async def export_pdf(blueprint_id: str):
    if blueprint_id not in blueprints_db:
        raise HTTPException(status_code=404, detail="Blueprint not found")
    
    data = blueprints_db[blueprint_id]
    idea = data["idea"]
    bp = data["blueprint"]
    
    pdf = PDF()
    pdf.add_page()
    
    # Title Page Info
    pdf.set_font('Helvetica', 'B', 24)
    pdf.set_text_color(15, 23, 42)
    pdf.ln(40)
    pdf.multi_cell(0, 15, f'Blueprint Report:\n{idea}', align='C')
    pdf.ln(20)
    pdf.set_font('Helvetica', '', 12)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 10, 'Comprehensive Strategic Analysis and Launch Roadmap', 0, 1, 'C')
    pdf.add_page()
    
    # Market Analysis
    pdf.chapter_title('1. MARKET ANALYSIS')
    ma = bp['market_analysis']
    pdf.section_body(f"Region Focus: {ma.get('region_focus', 'Global')}")
    
    # Market Table
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(40, 10, 'Category', 1)
    pdf.cell(60, 10, 'Size', 1)
    pdf.cell(40, 10, 'Growth', 1)
    pdf.ln()
    pdf.set_font('Helvetica', '', 10)
    for label, obj in [('TAM', ma['tam']), ('SAM', ma['sam']), ('SOM', ma['som'])]:
        pdf.cell(40, 10, label, 1)
        pdf.cell(60, 10, obj['amount'], 1)
        pdf.cell(40, 10, obj.get('growth', 'N/A'), 1)
        pdf.ln()
    pdf.ln(5)
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 10, 'Key Trends:', 0, 1)
    pdf.set_font('Helvetica', '', 10)
    for trend in ma['trends']:
        pdf.cell(0, 8, f"- {trend}", 0, 1)
    pdf.ln(5)

    # Competitive Landscape
    pdf.chapter_title('2. COMPETITIVE LANDSCAPE')
    cl = bp['competitive_landscape']
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 10, 'Competitor', 1)
    pdf.cell(100, 10, 'Description', 1)
    pdf.cell(30, 10, 'Share', 1)
    pdf.ln()
    pdf.set_font('Helvetica', '', 10)
    for comp in cl['competitors']:
        pdf.cell(50, 10, comp['name'], 1)
        pdf.cell(100, 10, comp['description'][:60] + '...', 1)
        pdf.cell(30, 10, comp['share'], 1)
        pdf.ln()
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 10, 'Strategic Moat:', 0, 1)
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(0, 5, cl['moat'])
    pdf.ln(5)

    # User Personas
    pdf.chapter_title('3. USER PERSONAS')
    for p in bp['personas']:
        pdf.set_font('Helvetica', 'B', 11)
        pdf.cell(0, 10, f"{p['name']} ({p['segment']})", 0, 1)
        pdf.set_font('Helvetica', '', 10)
        pdf.cell(0, 8, f"Goals: {', '.join(p['goals'])}", 0, 1)
        pdf.cell(0, 8, f"Pain Points: {', '.join(p['pain_points'])}", 0, 1)
        pdf.ln(2)
    pdf.ln(5)

    # MVP Spec
    pdf.chapter_title('4. MVP SPECIFICATIONS')
    ms = bp['mvp_spec']
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 8, 'Core Features:', 0, 1)
    pdf.set_font('Helvetica', '', 10)
    for f in ms['features']:
        pdf.cell(0, 6, f"- {f}", 0, 1)
    pdf.ln(2)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 8, 'Key User Flows:', 0, 1)
    pdf.set_font('Helvetica', '', 10)
    for f in ms['user_flows']:
        pdf.cell(0, 6, f"- {f}", 0, 1)
    pdf.ln(5)

    # GTM & Investors
    pdf.chapter_title('5. GTM & FUNDING STRATEGY')
    gtm = bp['gtm_strategy']
    pdf.section_body(f"Messaging: {gtm['messaging']}")
    pdf.section_body(f"Channels: {', '.join(gtm['channels'])}")
    pdf.section_body(f"Target Seed Funding: {bp['budget_and_team']['cost']}")
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 10, 'Recommended Investors:', 0, 1)
    pdf.set_font('Helvetica', '', 10)
    for inv in bp['investor_suggestions']:
        pdf.cell(0, 8, f"- {inv['name']} ({inv['focus']}) - Fit Score: {inv['fit_score']}%", 0, 1)

    pdf_output = pdf.output()
    return StreamingResponse(
        io.BytesIO(pdf_output),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=ZeroToOne_Blueprint_{idea.replace(' ', '_')}.pdf"}
    )

@app.get("/blueprint/{blueprint_id}")
async def get_blueprint(blueprint_id: str):
    if blueprint_id not in blueprints_db:
        raise HTTPException(status_code=404, detail="Blueprint not found")
    return blueprints_db[blueprint_id]

@app.post("/regenerate-section")
async def regenerate_section(request: RegenerateRequest):
    if not request.api_key or not request.api_key.strip():
        raise HTTPException(status_code=400, detail="Gemini API key is required.")
    
    if request.id not in blueprints_db:
        raise HTTPException(status_code=404, detail="Blueprint not found")
    
    idea = blueprints_db[request.id]["idea"]
    current_blueprint = blueprints_db[request.id]["blueprint"]
    
    section_map = {
        "market_analysis": MarketAnalysis,
        "competitive_landscape": CompetitiveLandscape,
        "personas": List[Persona],
        "mvp_spec": MVPSpec,
        "budget_and_team": BudgetAndTeam,
        "gtm_strategy": GTMStrategy,
        "timeline": Timeline,
        "investor_suggestions": List[Investor]
    }
    
    schema = section_map.get(request.section)
    if not schema:
        raise HTTPException(status_code=400, detail="Invalid section name")
    
    prompt = f"Refine the {request.section} for the startup idea: {idea}. Context: {current_blueprint}"
    
    try:
        updated_data = await call_llm_with_retry(prompt, schema, request.api_key)
        if isinstance(updated_data, list):
            blueprints_db[request.id]["blueprint"][request.section] = [i.model_dump() for i in updated_data]
        else:
            blueprints_db[request.id]["blueprint"][request.section] = updated_data.model_dump()
            
        return blueprints_db[request.id]
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
